language: node_js
node_js:
    - 'node'
    - '8'
    - '6'
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - npm run ci
addons:
    chrome: stable